app:
  host: 127.0.0.1
  port: 15003
  timeout: 4s
  idle_timeout: 30s

db:
  host: 127.0.0.1
  port: 5432
  username: ms4me
  password: p4ssw0rd
  dbname: ms4me

sso:
  host: 127.0.0.1
  port: 15001
