app:
  host: 0.0.0.0
  port: 15001
  jwt_secret: 64072d85-79df-4d44-8bb0-9eb86886de0b
  jwt_TTL: 48h

db:
  host: 127.0.0.1
  port: 5432
  username: your_username
  password: your_password
  name: your_dbname
