debug: true
http:
  host: 127.0.0.1
  port: 15004
  timeout: 4s
  idle_timeout: 30s

centrifugo:
  ping_interval: 0s # how often server-to-client pings
  pong_timeout: 0s # timeout for client answer on ping
  expiration_time: 5m

sso:
  host: 127.0.0.1
  port: 15001

db:
  host: 127.0.0.1
  port: 5432
  username: ms4me
  password: p4ssw0rd
  dbname: ms4me
